import type { RecipeCard } from './types'

// TEST-ONLY fallback data, shown when the backend returns zero recipes
// (e.g. an empty/unseeded dev database) so the grid layout can still be
// reviewed. Never used when the API genuinely errors or is unreachable.
export const PLACEHOLDER_RECIPES: RecipeCard[] = [
  {
    id: 'placeholder-1',
    slug: 'salted-caramel-tart',
    title: 'Salted Caramel Tart',
    thumbnail_url: 'https://picsum.photos/seed/caramel-tart/480/640',
    dish_category: 'baked_goods',
    course: 'dessert',
    primary_method: 'baking',
    difficulty: 'intermediate',
    total_time_mins: 75,
    taste_tags: ['sweet', 'rich'],
    dietary_flags: ['vegetarian'],
    calories: 420,
    avg_rating: 4.7,
    rating_count: 128,
    cuisine_origin: ['French'],
  },
  {
    id: 'placeholder-2',
    slug: 'spicy-caramel-chicken',
    title: 'Spicy Caramel Chicken',
    thumbnail_url: 'https://picsum.photos/seed/caramel-chicken/480/640',
    dish_category: 'rice_dishes',
    course: 'main',
    primary_method: 'braising',
    difficulty: 'beginner',
    total_time_mins: 45,
    taste_tags: ['spicy', 'savory'],
    dietary_flags: ['gluten_free'],
    calories: 560,
    avg_rating: 4.5,
    rating_count: 94,
    cuisine_origin: ['Thai'],
  },
  {
    id: 'placeholder-3',
    slug: 'brown-butter-caramel-cookies',
    title: 'Brown Butter Caramel Cookies',
    thumbnail_url: 'https://picsum.photos/seed/caramel-cookies/480/640',
    dish_category: 'baked_goods',
    course: 'dessert',
    primary_method: 'baking',
    difficulty: 'beginner',
    total_time_mins: 40,
    taste_tags: ['sweet', 'buttery'],
    dietary_flags: ['vegetarian'],
    calories: 210,
    avg_rating: 4.9,
    rating_count: 302,
    cuisine_origin: ['American'],
  },
  {
    id: 'placeholder-4',
    slug: 'caramelized-onion-soup',
    title: 'Caramelized Onion Soup',
    thumbnail_url: 'https://picsum.photos/seed/onion-soup/480/640',
    dish_category: 'soups',
    course: 'starter',
    primary_method: 'simmering',
    difficulty: 'intermediate',
    total_time_mins: 90,
    taste_tags: ['savory', 'umami'],
    dietary_flags: ['vegetarian'],
    calories: 280,
    avg_rating: 4.6,
    rating_count: 61,
    cuisine_origin: ['French'],
  },
  {
    id: 'placeholder-5',
    slug: 'caramel-glazed-salmon',
    title: 'Caramel-Glazed Salmon',
    thumbnail_url: 'https://picsum.photos/seed/glazed-salmon/480/640',
    dish_category: 'seafood',
    course: 'main',
    primary_method: 'roasting',
    difficulty: 'intermediate',
    total_time_mins: 35,
    taste_tags: ['sweet', 'savory'],
    dietary_flags: ['dairy_free', 'gluten_free'],
    calories: 390,
    avg_rating: 4.4,
    rating_count: 47,
    cuisine_origin: ['Japanese'],
  },
  {
    id: 'placeholder-6',
    slug: 'sticky-toffee-pudding',
    title: 'Sticky Toffee Pudding',
    thumbnail_url: 'https://picsum.photos/seed/toffee-pudding/480/640',
    dish_category: 'baked_goods',
    course: 'dessert',
    primary_method: 'baking',
    difficulty: 'advanced',
    total_time_mins: 80,
    taste_tags: ['sweet', 'rich'],
    dietary_flags: ['vegetarian'],
    calories: 480,
    avg_rating: 4.8,
    rating_count: 176,
    cuisine_origin: ['American'],
  },
  {
    id: 'placeholder-7',
    slug: 'caramelized-plantains',
    title: 'Caramelized Plantains',
    thumbnail_url: 'https://picsum.photos/seed/plantains/480/640',
    dish_category: 'sides',
    course: 'starter',
    primary_method: 'frying',
    difficulty: 'beginner',
    total_time_mins: 20,
    taste_tags: ['sweet'],
    dietary_flags: ['vegan', 'gluten_free'],
    calories: 240,
    avg_rating: 4.3,
    rating_count: 38,
    cuisine_origin: ['Kenyan'],
  },
  {
    id: 'placeholder-8',
    slug: 'dulce-de-leche-crepes',
    title: 'Dulce de Leche Crepes',
    thumbnail_url: 'https://picsum.photos/seed/dulce-crepes/480/640',
    dish_category: 'breakfast',
    course: 'breakfast',
    primary_method: 'pan-frying',
    difficulty: 'intermediate',
    total_time_mins: 50,
    taste_tags: ['sweet'],
    dietary_flags: ['vegetarian'],
    calories: 340,
    avg_rating: 4.6,
    rating_count: 83,
    cuisine_origin: ['Mexican'],
  },
  {
    id: 'placeholder-9',
    slug: 'maple-caramel-porridge',
    title: 'Maple Caramel Porridge',
    thumbnail_url: 'https://picsum.photos/seed/maple-porridge/480/640',
    dish_category: 'breakfast',
    course: 'breakfast',
    primary_method: 'simmering',
    difficulty: 'beginner',
    total_time_mins: 15,
    taste_tags: ['sweet', 'comforting'],
    dietary_flags: ['vegan'],
    calories: 310,
    avg_rating: 4.2,
    rating_count: 29,
    cuisine_origin: ['American'],
  },
  {
    id: 'placeholder-10',
    slug: 'caramel-miso-eggplant',
    title: 'Caramel Miso Eggplant',
    thumbnail_url: 'https://picsum.photos/seed/miso-eggplant/480/640',
    dish_category: 'vegetables',
    course: 'main',
    primary_method: 'roasting',
    difficulty: 'intermediate',
    total_time_mins: 40,
    taste_tags: ['umami', 'sweet'],
    dietary_flags: ['vegan', 'gluten_free'],
    calories: 260,
    avg_rating: 4.7,
    rating_count: 55,
    cuisine_origin: ['Japanese'],
  },
]
